/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


enum Operation {
  Operation_ADD = 1,
  Operation_SUBTRACT = 2,
  Operation_MULTIPLY = 3,
  Operation_DIVIDE = 4
};

typedef BOOL OperationTwo;

@interface MessageExistsException : NSException <TBase, NSCoding> {
  NSString * __message;

  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface Message : NSObject <TBase, NSCoding> {
  NSString * __text;
  NSString * __date;

  BOOL __text_isset;
  BOOL __date_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=text, setter=setText:) NSString * text;
@property (nonatomic, retain, getter=date, setter=setDate:) NSString * date;
#endif

- (id) init;
- (id) initWithText: (NSString *) text date: (NSString *) date;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) text;
- (void) setText: (NSString *) text;
#endif
- (BOOL) textIsSet;

#if !__has_feature(objc_arc)
- (NSString *) date;
- (void) setDate: (NSString *) date;
#endif
- (BOOL) dateIsSet;

@end

@interface User : NSObject <TBase, NSCoding> {
  NSString * __name;

  BOOL __name_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
#endif

- (id) init;
- (id) initWithName: (NSString *) name;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

@end

@protocol BulletinBoard <NSObject>
- (void) add: (Message *) msg;  // throws MessageExistsException *, TException
- (NSMutableArray *) get;  // throws TException
@end

@interface BulletinBoardClient : NSObject <BulletinBoard> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface BulletinBoardProcessor : NSObject <TProcessor> {
  id <BulletinBoard> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithBulletinBoard: (id <BulletinBoard>) service;
- (id<BulletinBoard>) service;
@end

@protocol UserService <NSObject>
- (void) add: (User *) user;  // throws TException
- (NSMutableArray *) get;  // throws TException
@end

@interface UserServiceClient : NSObject <UserService> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface UserServiceProcessor : NSObject <TProcessor> {
id <UserService> mService;
NSDictionary * mMethodMap;
}
- (id) initWithUserService: (id <UserService>) service;
- (id<UserService>) service;
@end

@interface testConstants : NSObject {
}
+ (int32_t) INT32CONSTANT;
@end
